# Generated by Django 4.0.4 on 2022-05-19 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0002_contact_students_contact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='students',
        ),
        migrations.AddField(
            model_name='contact',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
