# Generated by Django 4.0.4 on 2022-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_remove_contact_students_contact_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='media/new.jpg', null=True, upload_to='media'),
        ),
    ]
