# Generated by Django 4.0.4 on 2022-05-19 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0005_alter_contact_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Gonderi',
        ),
    ]
