# Generated by Django 4.0.4 on 2022-05-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_rename_contact_gonderi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gonderi',
            old_name='students',
            new_name='kullanici',
        ),
    ]
