# Generated by Django 4.0.4 on 2022-05-19 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0007_rename_students_gonderi_kullanici'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gonderi',
            old_name='first_name',
            new_name='icerik',
        ),
        migrations.RemoveField(
            model_name='gonderi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gonderi',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='gonderi',
            name='message',
        ),
        migrations.RemoveField(
            model_name='gonderi',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='gonderi',
            name='title',
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
