# Generated by Django 4.0.4 on 2022-05-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_gonderi_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gonderi',
            name='email',
        ),
    ]
