# Generated by Django 4.0.4 on 2022-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_remove_gonderi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderi',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
