# Generated by Django 4.0.4 on 2022-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0012_remove_gonderi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderi',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
