# Generated by Django 4.0.4 on 2022-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0013_gonderi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonderi',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
