# Generated by Django 4.0.4 on 2022-05-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_gonderi_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gonderi',
            name='students',
        ),
    ]
