# Generated by Django 4.0.4 on 2022-05-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_gonderi_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gonderi',
        ),
    ]
